### ISSUE TITLE
load-sdk's callback is never called

### ISSUE THREAD

**Issue by featalion** [netpyoung/fb-sdk-cljs#2]
Hi,

I try to use the library and found weird (at least for me) behaviour.
When I use it in development mode it works OK (with figwheel, started from REPL). But after making an uberjar and launch from command line, it doesn't.

Tags are there:

```html
<html>
  <head>
    ...
    <script id="fb-sdk-cljs" async="" src="//connect.facebook.net/en_US/sdk.js"></script>
    ...
    <style type="text/css">{ FB STYLESHEET }</script>
  </head>
  <body>
    ...
    <div id="fb-root" class=" fb-reset">...</div>
  </body>
</html>
```

It means, that `load-sdk` is called and finished it work. In the network monitor I see, that FB SDK JS is loaded, too. But, for some reason, callback is not called.

Do you have any ideas why it happens? I'm glad to have any help here!

**Comment by featalion** [comment]
Seems like `window.fbAsyncInit` callback is not set in the uberjared version of the app. I don't know the reason yet.

**Comment by netpyoung** [comment]
sorry for inconvenience.

actually, `load-sdk` function 
https://github.com/netpyoung/fb-sdk-cljs/blob/master/src/fb_sdk_cljs/core.cljs#L26
load `//connect.facebook.net/en_US/sdk.js` automatically.


~~~html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>hi, world!</title>
  </head>
  <body>
    <h1>fb-sdk-cljs</h1>
    <div id="container"></div>
    <script type="text/javascript" src="js/compiled-clojurescript.js"></script>
  </body>
</html>
~~~

so, i think When you remove
`    <script id="fb-sdk-cljs" async="" src="//connect.facebook.net/en_US/sdk.js"></script>`
on header, it will be fine.

If not, feed back to me please.
and I will check it my self too.

**Comment by featalion** [comment]
OK, I found the issue. During compilation, optimisation, and minification `cljsbuild` compiler transforms `.-fbAsyncInit` into short version so that expected `window.fbAsyncInit = myCallback;` becomes `window.xx = myCallback;`. To fix the issue I pass `:externs` option to the compiler in the `project.clj`.

```clj
{:profiles
 {:uberjar ;; or any other profile you want to minify and optimise the code
  {:cljsbuild
   {:builds
    {:app
     {:source-paths ^:replace ["src/cljs"]
      :compiler
      {:optimizations :advanced
       :externs ["externs/fbsdk.js"]
       :pretty-print false}}}}}}}
```

Create directory called `externs` in the root. In the directory I made file `fbsdk.js` with the next content:

```js
window.fbAsyncInit = function(){};
```

that says compiler to do not strip `fbAysncInit` on `window`, that resolves my issue.

**Comment by netpyoung** [comment]
Thank you!!

**Comment by featalion** [comment]
> so, i think When you remove
> <script id="fb-sdk-cljs" async="" src="//connect.facebook.net/en_US/sdk.js"></script>
> on header, it will be fine.

I posted those tags to acknowledge, that they are in place and created by `load-sdk` function, and to point, that callback doesn't work.

**Comment by featalion** [comment]
Thank you for the library, btw ( :
